### ISSUE TITLE
Should we say something about short duration connections?

### ISSUE THREAD

**Issue by huitema** [ietf-wg-ccwg/rfc5033bis#10]
In the Internet, most connections never exit Slow-Start. RFC 5033 kind of explicitly focuses on the long duration connections, because at the time of writing the accepted rule was that the 10% long duration connections were were causing 90% of traffic. I don't know whether that's still true.

**Comment by VMatrix1900** [comment]
With the usage of QUIC, more short-lived connections are aggregated into a long connection.
