### ISSUE TITLE
Section 5 editorial comments

### ISSUE THREAD

**Issue by gwhiteCL** [ietf-wg-ccwg/rfc5033bis#100]
1. The second paragraph of 5 reads:

> In general, measurements from Internet-scale deployments will not expose the properties of operation in these scenarios, as they are statistically small.

I probably agree that _some_ of the scenarios are statistically small, and may remain that way in the future, but others aren't all that statistically small even today and/or could become less small in the foreseeable future.  AQM is now reasonably widely deployed, anyone with Starlink internet sees varying delay, most Wi-Fi links exhibit periodic transient link disconnections during channel scanning, etc.  I'd suggest something like:

> In general, measurements from Internet-scale deployments may not expose the properties of operation in each these scenarios, as they are not as ubiquitous as the General Use scenarios.

2. The first paragraph of 5.7 Transient Events reads:

> The proposal SHOULD consider how the proposed congestion control algorithm would perform in the presence of transient events such as sudden onset of congestion, a routing change, or a mobility event. Routing changes, link disconnections, intermittent link connectivity, and mobility are discussed in more detail in Section 17 of [[Tools](https://www.ietf.org/archive/id/draft-ietf-ccwg-rfc5033bis-03.html#Tools)].

The [Tools] link takes one to https://datatracker.ietf.org/doc/draft-irtf-tmrg-tools, where Section 17 provides us with: 

> 17.  Using the Tools Presented in this Document
> 
>     [To be done.]

Was this intended to be a joke?  .... Actually, I think you meant Section 16.

**Comment by gorryfair** [comment]
This is indeed long-since expired: title: Tools for the Evaluation of Simulation and Testbed Scenarios target: "https://datatracker.ietf.org/doc/draft-irtf-tmrg-tools" seriesinfo: Work in Progress date: 2007-7 author: - ins: S. Floyd - ins: E. Kohler.
