### ISSUE TITLE
"Forbidden" in Section 2

### ISSUE THREAD

**Issue by ekinnear** [ietf-wg-ccwg/rfc5033bis#109]
From @gloinul's review:

> Algorithms that are designed for special environments (e.g., data centers) and forbidden from use in the Internet would, of course, instead seek real-world data for those environments.
 
I reacted to the use of “forbidden” in this sentence. Would not “not intended at all for use in the Internet” be a better formulation? Because forbidden want me to invoke the Protocol Police if someone ever attempted to use it.

**Comment by gorryfair** [comment]
For me, this was meant to be stronger than "not intended", more like "confined to a limited to a controlled environment". 

RFC 8799 describes some of these cases, and could be a useful reference?

**Comment by gloinul** [comment]
So I think a stronger wording is fine. But, an alternative formulation would be good that doesn't imply that you might get the protocol police after you.
