### ISSUE TITLE
General-purpose transport or standard congestion control algorithm

### ISSUE THREAD

**Issue by zaheduzzaman** [ietf-wg-ccwg/rfc5033bis#124]
The title of section 5.2.1 mentions general-purpose transports but the content really about comparing against standard congestion control algorithms, I suggest to reflect that in the section title. 

https://github.com/ietf-wg-ccwg/rfc5033bis/blob/660760a9375d713c6586b11eb337235b51e7af50/draft-ietf-ccwg-rfc5033bis.md?plain=1#L418

**Comment by gorryfair** [comment]
Hmmm: This was originally conceived as General-Purpose v Real-Time (next section). 
If we change this to "standard general-purpose congestion control algorithms" , does it then make "real-time look non-standard - so ought that now be "standard real-time congestion control algorithms"?
- Would that help?

**Comment by zaheduzzaman** [comment]
It was not that clear that it was supposed to convey "general-purpose" VS "real-time". But my main point was that if this is all about congestion control for general purpose transport then lets say that.

- Competing with general purpose congestion control 
- Competing with real-time congestion control
