### ISSUE TITLE
OPSDIR Review

### ISSUE THREAD

**Issue by martinduke** [ietf-wg-ccwg/rfc5033bis#132]
From Juergen Schoenwaelder:

The document provides guidelines for the IETF when evaluating new
proposed congestion control algorithms. While important, this document
is not directly influencing network operations.

This update grows the document from 10 pages ([RFC 5033](https://datatracker.ietf.org/doc/rfc5033/)) to 25 pages. I
found the draft well structured and easy to read and all content
appears to be well justified. The draft provides helpful advice to
everybody involved in the development and evaluation of congestion
control algorithms.

- I am wondering whether section 7.1.1 really should be a sub-section
  of 7.1, which implies that a network circuit breaker are viewed as a
  special kind of an active queue management technique. Keeping the
  sub-sections a flat list of special cases may simplify things. I
  also found the title of section 7.1.1 a bit longish compared to the
  other section titles. Perhaps turning 7.1.1 into "7.2 Interaction
  with Network Transport Circuit Breakers" or just "7.2 Network
  Transport Circuit Breakers" leads to a simpler structure.

- Similarly, I wonder whether sub-section 7.7.1 should be lifted up as
  well. Path changes are not necessarily a transient event. Perhaps
  7.7.1 should become "7.X Changes in the Path" (dropping sudden as
  well). The point made in the text is that paths are not static, they
  may change.

Perhaps	the above two comments make no sense, then just	ignore them.
I just thought I share them since they came up during my first time
read of the document.

**Comment by gorryfair** [comment]
The organisation could be better, but I don't see a network circuit breaker (as policing) as a kind of an active queue management technique (as a scheduling/queuing action), they are rather different in operation and design, so I'd rather keep these separate, and just move CB's up one level?
If we did that, i wouldn't object to 7.7.1 being made 7.8.
