### ISSUE TITLE
Someone with admin privilege should check how this repo is set

### ISSUE THREAD

**Issue by huitema** [ietf-wg-ccwg/rfc5033bis#19]
I just entered a couple of PR, and the final github action fails. I suspect this is an issue of rights and privileges for github actions writing to gh-pages, but only an admin has the rights to check that.

**Comment by theri** [comment]
I just changed the Workflow permissions to "Read and Write" according to [this page](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-the-default-github_token-permissions) on the organization level.
According to the [Deploy to Github pages tutorial](https://github.com/marketplace/actions/deploy-to-github-pages), this is a necessary step to get it to work.

Is it working now?
