### ISSUE TITLE
We ought to explain the importance of starvation prevention more than the measure of fairness

### ISSUE THREAD

**Issue by gorryfair** [ietf-wg-ccwg/rfc5033bis#21]
Issue possibly related to #9, but more focussed on refocus away from a fairness evaluation.

When a transport uses a path to send packets (i.e. a flow), this can impact other Internet flows (possibly from or to other endpoints) that share the capacity of any common network device or link (i.e., are multiplexed) along the path.  In turn, this can result in variation in capacity, loss, or additional latency. Transports and network layer scheduling can be designed to offer fairness between sharing flows. This comes with both strengths and weaknesses - it can reduce collateral damage to other flows; but it also can motivate the use of additional flows to gain additional network resource. 

* Transport proposals need to be evaluate and avoid inducing flow starvation to the other flows that share resources along the path they use.
* Transports proposals need to be evaluate and ensure they treat a loss of all feedback (e.g., expiry of a retransmission time out) as an indication of persistent congestion.

**Comment by martinduke** [comment]
Gorry will start with a PR that defines the terms; then we can talk about what to emphasize.
