### ISSUE TITLE
include guidance from rfc7141

### ISSUE THREAD

**Issue by rscheff** [ietf-wg-ccwg/rfc5033bis#3]
rfc7141 partially updates rfc5033; include relevant sections in the -bis document

**Comment by martinduke** [comment]
7141 does not mention 5033, so can you be more specific?

**Comment by martinduke** [comment]
Oct 12: Pinged @rscheff to follow up

**Comment by rscheff** [comment]
IIRC, it was due to rfc7141 updating rfc2914; rfc2914 is mentioned and referenced at numerous points throughout the 5033 document.

5033bis should heed the advice from 7141 around marking probabiliy taking into consideration packet sizes rather than only the packets themselves. At least this train of thought is the most likely one, which was had in my mind at the time.

**Comment by martinduke** [comment]
Editors: we suspect that this question is orthogonal to the purpose of this document; will look more carefully at the reference.

**Comment by martinduke** [comment]
It turns out that 7141 does have recommendations on response to congestion signals from the network, not just AQM recommendations (See Sec 2.3 and 2.4 for a good summary).
