### ISSUE TITLE
What about Cubic and BBR?

### ISSUE THREAD

**Issue by huitema** [ietf-wg-ccwg/rfc5033bis#4]
When reading the document status section, that was my first reaction. The purpose of the document is to provide guidelines about protocols that are deemed safe for the Internet, with the assumption that wide scale deployments will only happen after approval by the IETF. With Cubic and BBR we have two examples of massive deployments without any such formal approval. In fact, discussions in the IETF would have quickly pointed out issues such as Cubic amplifying buffer bloat, or BBR having no particular guarantee of fairness, even when sharing with itself. Yet both protocols have been deployed at massive scale. What does that say about the "real" status of this document?

**Comment by NicoKos** [comment]
This is a very good point. I feel that the document could at least mention this issue.

**Comment by acbegen** [comment]
It need to acknowledge it not just mention. There are so many different types of networks and applications (or services) where some of the "hard" rules can be easily bent. Not accepting that does not change the fact.

**Comment by martinduke** [comment]
Is the intent to mention these non-IETF projects as motivation, or adjust the normative parts in some way?
