### ISSUE TITLE
Is Multicast in scope?

### ISSUE THREAD

**Issue by gorryfair** [ietf-wg-ccwg/rfc5033bis#40]
Discussed at IETF-118. 

At least we can mention Sect 4 of Multicast UDP Usage Guidelines in RFC8085.

**Comment by ekinnear** [comment]
IETF 118:
- Possibility that we could rule this out of scope
- Also some interest in this as a separate document that comes after the -bis

**Comment by gloinul** [comment]
So just to provide the background for my question. The Reliable Multicast Transport WG (RMT) did produce two expermential congestion control specifications for multicast:

- [Wave and Equation Based Rate Control (WEBRC) Building Block RFC 3738](https://datatracker.ietf.org/doc/rfc3738/)
- [TCP-Friendly Multicast Congestion Control (TFMCC): Protocol Specification RFC 4654](https://datatracker.ietf.org/doc/rfc4654/)
- [NORM Specification](https://datatracker.ietf.org/doc/rfc3940/)

So these specifications exists. Most mulitcast deployments are done in controlled environments however, with [Automatic Multicast Tunneling] (https://datatracker.ietf.org/doc/rfc7450/) multicast traffic these days have more probability to occur across links where this traffic would share bottlenecks with other unicast traffic. However, this amount of traffic is still normally bit-rate bound so it might be considered just in-elastic and consuming the bit-rate it does. 

I also want to state that I am fine with declaring multicast out of scope, but maybe some information about that there exist algorithms should be includeded in the draft. So an explicit out of scope with some background section/appendix.

**Comment by martinduke** [comment]
We will put it out of scope and point to RFC 8085

**Comment by martinduke** [comment]
Closed by #49

**Comment by theri** [comment]
Sorry, just reading through these changes now -- Why does a PR on multi**path** close an issue on multi**cast**? Am I missing something here?

**Comment by gorryfair** [comment]
Whoops, that does not seem correct, re-opened this issue.

**Comment by martinduke** [comment]
To answer @gloinul more directly, I don't think this draft is in the business of listing algorithms unless it requires new proposals to be measured against them, and not even that if the topic is out of scope. 5033bis is not a congestion control tutorial.

**Comment by gloinul** [comment]
@martinduke I think it is a question of how one resolve this and if one declares it out of scope. Are we explicitly stating something like this: 

Multicast congestion control algorithms is out scope, and the rules and requirements within this specification has not been evaluated on their applicability for multicast congestion control. Future work on multicast congesiton control to specify new algorithms or update existing [webrc][TFMCC] will have to evaluate what is applicable and if additional requirements are necessary.
