### ISSUE TITLE
Add a section on CCA development  lifecycle

### ISSUE THREAD

**Issue by mattmathis** [ietf-wg-ccwg/rfc5033bis#44]
Replace all or part of section 2, "document status" with a new section on CCA development lifecycles.   Include the following major phases and constraints.

Pilot (private evaluation)
 - Authors MUST maintain full control and the ability to withdraw all instances
 - Sources and binaries are not published outside of the author's domain
 - It includes instrumentation for data rate, loss, delay , ECN marking, etc
 - And infrastructure to harvest telemetry from all instances
 - Continuous A/B testing against legacy algorithms
 - Include methods for estimating impact on other protocols and algorithms 
 - I-D published and revised as the pilot matures

Pre-deployment and public evaluation
 - Published sources
 - Opt-in usage only
 - I-D kept up-to-date and progresses towards RFC (experimental or info status)
 - Authors maintain instrumentation, telemetry and continuous A/B testing for early adopters
 - Widespread evaluation by the broader community
   - A/B testing
   - Testing in challenging and unexpected network environments
 - Open a wiki evaluation doc
  - Conformance statement for RFC5033bis (this doc)
  - Summaries and references of external evaluations
    - Including details necessary for others to duplicate to expand on the experiments
  - If there are algorithm changes, add appropriate annotation to older reports and solicit updated results

Approval for wider deployment
 - Requires RFC publication(s) covering:
  - Algorithm spec
  - Snapshot of the evaluation wiki
  - Deployment guidelines
     - Most important question: Is it safe for unattended use by non-experts?
 - Preserve (and maintain) the pre deployment implementation as a reference for future conformance testing.
 - Evaluation wiki lives on to capture unexpected events or problems discovered later

**Comment by martinduke** [comment]
Editors: there are several good ideas in here, but this list is very prescriptive and implies requirements that are well beyond the capabilities of many proponents.

We don't object to a rewrite of Sec 2, but these aspects would have to be toned down.

Assigning to @mattmathis to see if he can produce a PR that addresses those concerns. He is welcome to close this issue if he prefers.

**Comment by huitema** [comment]
I think it could be summarized as "be prudent with what you deploy, or where you test." Which is indeed good practice.

But we should be careful to not appear as trying to police developers, because in reality we have zero police power. Advice is good, mandates are likely to be ignored and cause developers to ignore the document completely. Remember, nobody asked the IETF's permission before deploying Cubic...

**Comment by martinduke** [comment]
Closing this issue, as it's through IETF Last Call
