### ISSUE TITLE
What does impact on transport protocols mean?

### ISSUE THREAD

**Issue by huitema** [ietf-wg-ccwg/rfc5033bis#5]
The Guidelines section asks developers of new congestion control algorithms to discuss the "Impact on Standard TCP, SCTP [[RFC2960](https://rscheff.github.io/rfc5033bis/draft-scheffenegger-congress-rfc5033bis.html#RFC2960)], and DCCP [[RFC4340](https://rscheff.github.io/rfc5033bis/draft-scheffenegger-congress-rfc5033bis.html#RFC4340)]." Maybe I am overly sensitive, but this way of discussing the issue feels dated, from a time when transport and congestion control where specified jointly. I think that ceased to be the case many years ago, for example with implementations of TCP providing choices between multiple congestion algorithms. (Indeed, DCCP itself provides a choice between two algorithms.) The Bis draft should probably present the issue differently.

**Comment by NicoKos** [comment]
Speaking of fairness, I also wonder if there is an accurate definition for it. 
There has been activity on the topic at the IETF (on in academia) : 
https://datatracker.ietf.org/doc/html/draft-briscoe-tsvarea-fair-02 
https://datatracker.ietf.org/doc/html/draft-briscoe-tsvwg-relax-fairness-01
https://dl.acm.org/doi/abs/10.1145/3487552.3487834 

should this be discussed in the draft ?

**Comment by ekinnear** [comment]
Discussed at IETF 117: 
- Matt: Replace fairness with freedom from starvation. Fairness only makes sense at low bandwidth.
- Christian: Not focus entirely at fairness, non-starvation goal is good.
- Gorry: Suggestion to put it in other draft, but not in this one

Overall, get rid of it all together for now

**Comment by mirjak** [comment]
In academia a next metric is to look at harm rather than fairness: https://dl.acm.org/doi/10.1145/3365609.3365855

**Comment by huitema** [comment]
That's a pretty good reference, Mirja!

**Comment by huitema** [comment]
The reality is that Cubic has a horrific effect on the Internet: it is pretty efficient at building queues and making life terrible for others. The classic example is the parent busy on a video conference from home, and then seeing the perceived quality go down sharply because the teenager started downloading a movie...

Which means I would take "fairness with Cubic" with a huge grain of salt. As is, yes, let it run and get some bandwidth, but make sure that it gets seriously penalized, so there is an incentive to replace it by something better...

**Comment by mattmathis** [comment]
A more serious problem is harm to tiny transactions using any protocol.   They have to rely on timeouts for loss recovery.  I suggest replacing this with absolute upper bounds on loss rates.   E..g. see:  https://datatracker.ietf.org/doc/html/draft-mathis-tsvwg-safecc#name-bound-steady-state-losses

Likewise for excessive standing queues, and to a lessor extent excessive CE marks.
