### ISSUE TITLE
Wireless links are not special cases.

### ISSUE THREAD

**Issue by huitema** [ietf-wg-ccwg/rfc5033bis#6]
The guidelines section as discussion of "Difficult Environments", starting with "The proposed algorithms should be assessed in difficult environments such as paths containing wireless links."  Opinion may vary, but wireless links are probably now part of something between "a vast majority" and "a plurality" of the paths on the Internet.

**Comment by VMatrix1900** [comment]
I agree. Wireless serves the vast majority and are still increasing.

**Comment by martinduke** [comment]
Gorry and Martin: wireless constraints deserve their own section. Three different phenomena to discuss
- Non-congestion loss
-  Variable bandwidth on the path
- Jitter due to media access and link-layer retransmission
