### ISSUE TITLE
Section ## Active Queue Management (AQM) {#aqm}

### ISSUE THREAD

**Issue by gorryfair** [ietf-wg-ccwg/rfc5033bis#67]
This section is listed as a special case, which it is (kind of), but it seems rather out of place in that section - I think we might wish to move it to the previous section. Since the original BCP, AQM is more common and really ought to be considered in any new design - even if the design does not wish to optimise for this.

**Comment by martinduke** [comment]
Editors 1/16/24: Just add a sentence that AQMs are hard to detect, and therefore must be thought about -- cannot just ban use of a CC with AQM.

But this falls thematically in with the special cases.

**Comment by huitema** [comment]
AQ are only a problem if they introduce unexpected behavior. The classic example is rate limiting, for which BB had to introduce special code.

**Comment by gorryfair** [comment]
Although packet scheduling and policing are useful complimentary functions, I don't think they are AQM.
