### ISSUE TITLE
Abstract seems rather odd

### ISSUE THREAD

**Issue by gorryfair** [ietf-wg-ccwg/rfc5033bis#69]
Our abstract starts:
"The IETF's standard congestion control schemes have been widely shown
to be inadequate for various environments (e.g., high-speed networks,
wireless technologies such as 3GPP and WiFi, long distance satellite
links) and also in conflict with the needed, more isochronous,
behaviors of VoIP, gaming, and videoconferencing traffic."

... is it just me, or does "inadequate" and "at conflict" seem an odd BCP statement from the IETF itself.

**Comment by nealcardwell** [comment]
Agreed. How about something closer to:

"The IETF's standard congestion control schemes have been shown to have performance challenges in various environments (e.g., high-speed networks, cellular and WiFi wireless technologies, long distance satellite links) and also for interactive traffic workloads (VoIP, gaming, and videoconferencing)."

cc: @martinduke @mattmathis
