### ISSUE TITLE
Section 2 "Document Status" needs work

### ISSUE THREAD

**Issue by martinduke** [ietf-wg-ccwg/rfc5033bis#79]
Sec 2 leans heavy on the dated example of Highspeed TCP and drives pretty much everything to Experimental "until such time that the community better understands the solution space."

It says that experimental RFCs can either be those judged to be safe on the internet, or those intended for testbeds.

At this point, we probably understand enough to allow proposals to go for Proposed Standard.  The safe/testbed distinction also doesn't make sense -- we might want to standardize CCs for controlled environments, like DCTCP.

This needs a complete rewrite. It wouldn't hurt for that rewrite to also note that the IRTF is another venue, non-normatively.

**Comment by gorryfair** [comment]
I think a rewrite would help, but I'm think that could be too radical - we still do have proposals that ought ton be EXP either until deployment experience; or until we can agree they are "safe" for more general use. That doesn't seem to be a problem to me, but we ought to allow PS also. 

I agree we ought to mention IRTF.
