### ISSUE TITLE
Add motivation for specifying congestion control algorithms to Introduction?

### ISSUE THREAD

**Issue by theri** [ietf-wg-ccwg/rfc5033bis#84]
The Introduction correctly points out the following:
> We cannot say now whether the original authors of [[RFC5033](https://github.com/ietf-wg-ccwg/rfc5033bis/issues/new#RFC5033)] expected that developers would be somehow waiting for IETF review before widely deploying a congestion control algorithm over the Internet, but the examples of Cubic and BBR teach us that deployment of new algorithms is not in fact gated by publication of the algorithm as an RFC. Nevertheless, guidelines are important, if only to remind potential inventors and developers of the multiple facets of the congestion control problem.

The above text says guidelines for specifications are important, but such guidelines only make sense if there is a specification in the first place.
So I wonder if it's worth saying a few words here about why it's useful to specify/standardize congestion control algorithms.

A few thoughts on the benefits of specifying congestion control algorithms:
- Help get a shared understanding between implementers, operators, and other interested parties of how the algorithm works and how it is expected to behave (or explicit discussion of parameters and such which can lead to differences in behavior)
- As a result of the shared understanding: Make it easier for anyone, not just the initial proponents or main implementers, to point out current issues/limitations or suggest improvements  of a spec that is still in development, and make it easier to converge such changes to a consensus behavior

There may be more benefits. 
Though I wonder how to best capture the nuance of "Some documentation or artifacts are better than nothing, but an actual spec is better than just a snapshot for documentation or artifacts".

Do people think it'll be useful to add something along these lines to the document?

**Comment by gorryfair** [comment]
I can see this would be of value to someone considering submitting a proposal. It also may help them to justify the effort in writing this down. If we can find words that work, I'd like to consider adding something on this.

**Comment by alvestrand** [comment]
Guidelines on what to consider are good for anyone (those who design, those who implement and those who document).
The only place where guidelines could be used for enforcing something is where people wish to have congestion control algorithms published through the IETF. But that doesn't make them useless in other parts of the process.

(My friend who does CC for realtime media is developing his work through iterations of code, not iterations of documentation. Guidelines would still be useful for him.)
