### ISSUE TITLE
Flows sharing a bottleneck under Single Algorithm Behavior?

### ISSUE THREAD

**Issue by theri** [ietf-wg-ccwg/rfc5033bis#86]
This _might_ be an editorial issue, and/or I might be misunderstanding something:

Section 3.1 is explicitly scoped as Single Algorithm Behavior.

Subsection 3.1.4 starts with:
> In contexts where differing congestion control algorithms are used, it is important to understand whether an alternate congestion control algorithm can induce more harm to sharing flows than existing defined methods. 

Doesn't the use of "differing congestion control algorithms" imply that this subsection is about Mixed Algorithm Behavior, so it should be under Section 3.2?
Or am I missing a subtle nuance here, in which case I suggest clarifying why this text needs to be under 3.1? Or does it apply to both Single and Mixed Algorithm Behavior?

**Comment by gorryfair** [comment]
I changed to use the word "differing" ... was that the correct intent?

**Comment by theri** [comment]
Sorry, I don't follow, Gorry.
My question was: Why is text about "differing algorithms" under Section 3.1 "Single Algorithm Behavior"? And should this text be under Section 3.2 "Mixed Algorithm Behavior" instead?

**Comment by martinduke** [comment]
I agree with Reese. This subsection is redundant with the reference to bottlenecks at the start of the section, and further discussion of "significant negative impact" in the mixed algorithm section.

**Comment by martinduke** [comment]
Fixed by #89
