### ISSUE TITLE
Something very odd about section 3.1.4 (technical github problem?)

### ISSUE THREAD

**Issue by mwelzl** [ietf-wg-ccwg/rfc5033bis#92]
Hi,

In the "Editor's copy", there is a section 3.1.4. called "Avoiding Starvation of Flows sharing a bottleneck."
(side note: I suggest to update this title to "Avoiding Starvation of Flows Sharing a Bottleneck")

This section is also visible when I follow the link called: "Compare Editor's Copy to Individual Draft".

HOWEVER: the section is *not* a part of the .md file ???
How strange? How can this happen?

BTW, in terms of content, this section is useful to me, but perhaps not strictly necessary to include since section 3.1.1 exists.

**Comment by martinduke** [comment]
Yes, our editors' copy isn't building. I think we deleted this section because of 3.1.1, as you inferred.

**Comment by martinduke** [comment]
I believe this problem has fixed itself. Closing.
