### ISSUE TITLE
Mention that CCs should not impair the path for others

### ISSUE THREAD

**Issue by ekinnear** [ietf-wg-ccwg/rfc5033bis#97]
Raised at IETF 119: We may want to consider mentioning that you shouldn't impair the path for others.

**Comment by martinduke** [comment]
This was Lars's contribution.

**Comment by gorryfair** [comment]
Agree, let's keep the issue open and re-read the draft after all edits - at most I expect this would need to be called out earlier.

**Comment by gorryfair** [comment]
@ekinnear In 4.2, we have: "In contexts where differing congestion control algorithms are used, it is important to understand whether the proposed congestion control algorithm could result in more harm than previously defined algorithms to flows sharing a common bottleneck."
- Is this enough, or do you have a request for something section that needs attention?

**Comment by martinduke** [comment]
Eric is just recording Lars's comment at the mic. I'm fairly sure Lars hasn't read the draft, so as you said, let's make sure this is covered when we re-read it.

**Comment by nealcardwell** [comment]
IMHO "previously defined algorithms" is not exactly what we mean, and this could be made more precise: "previous standards-track algorithms (e.g. {{!RFC5681}}, {{!RFC9002}}, {{!RFC9438}})"

AFAICT the goal is to consider harm induced relative to the harm induced by Reno/CUBIC. There may be other experimental algorithms that become "defined", which are not intended as a yardstick by which to measure harm.

https://github.com/ietf-wg-ccwg/rfc5033bis/pull/108

**Comment by huitema** [comment]
We also have recommendations about bufferbloat and packet losses, which are also very much about "not causing harm to others". That plus #108 means we can probably close the issue.
