### ISSUE TITLE
Data centers with really small RTTs should be discussed as a special case

### ISSUE THREAD

**Issue by ekinnear** [ietf-wg-ccwg/rfc5033bis#98]
From IETF 119: Data centers with really small RTTs should be discussed as a special case

**Comment by ekinnear** [comment]
- @huitema: We need to be specific about what we mean by datacenter (e.g. Hadoop queries), please give some details about the data center scenarios that we want to take into account
- @larseggert: Typically you see proposals that rely on the fabric doing non-internet-y things, often there's combined implementation with the data plane, so we need to be specific there. Also saw some presentations this week about non-ethernet fabrics, need to describe what you see from your fabric and what you can then do from a congestion control perspective.
- Jeff Tantsura: Some spillover from IPPM, doesn't work on public internet and not intended to. Number of things being deployed today, massive clusters, 100,000 endpoints constantly talking to each other. Special congestion controllers are very much needed. Trying to keep CPU/GPU non-idle all the time. We need something that is fast within 1-2 RTTs, doesn't matter if done on endpoints, NICs, switches.

**Comment by gorryfair** [comment]
There are sets of specific network characteristics; some of this relies on non-IETF specs and it would help to know the interop requirements between implementations and also what the coexistence requirements are for other flows.
